server:
  port: 8085
spring:
  datasource:
    password: alpedo
    url: jdbc:postgresql://localhost:5432/Genius
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto : update
      show-sql: true
  sql:
    init:
      platform: postgres

